export const QuyenTat2007 = [

  'As I remember, I became a Christian on October 1, 2004 at Faith Jireh Christian Church, which was a day that changed my entire life. Before I believed in Jesus Christ, I was a very passive and bore person, and I did many negative things. However, after I believed in Jesus Christ, I began to change into a new person.',

  'Before I came to the United States, I was lived in Vietnam. There are no laws against alcohol or smoking, so I started drinking beer at the age of five. I drink beer during any banquet that I went, and I also took my dad’s beer at home to drink when he’s not at home. At the age of nine (I guess), I started to smoke too. Beside these, I watch read adult comic book that my friends brought to my house. Then things seem to be changing because I learned that I was going to the United States.',

  'In January 11, 2001, I finally came to the United States. I seem to be changed because I stop smoking and drinking because I did not meet the age to buy those items. Also, I have no friends at all and did not speak English, so I always isolated myself from the others. During lunch time, I always sat in the corner by myself and have my lunch. If I still have time left, I will sat there and wait until the class began. As time passed, things began to change again. This time I learned other bad things. I learned a lot of curses and bad words as I heard the people in school said everyday. I also learn how to use the internet, in which I use mostly on playing video games. Sometimes I even visit the adult web sites.',

  'In the summer of 2004, I have nothing to do, so my mother forced me to go to FJCC for tutoring. After the tutor, I was invited to an outdoor activity, which is BBQ, which was the first time I sing Christian songs and listen to prayer before we have our food. After this activity, I was also invited to the Friday night’s fellowship, and I accepted Jesus Christ as my personal savior there on October 1, 2004.',

  'Afterward, I attended every Friday’s fellowship. Later on, I was invited to the Sunday’s worship too. The people that attended these activities are very kind and always talked to me, which made me no longer isolated. I have to admit that church was sometime boring and not fun at all because I felt into sleep couple times. However, I learned many lessons about life. In addition, I began to change my negative hobbies and behavior. I didn’t smoke anymore, and I gradually stop drinking too. I didn’t visit the adult web sites as much as I did before, and my behavior was getting better too. However, there were still few things to change because I still saying bad words, and spent most of my time on playing video games.',

  'Eventually, I was a bad person before I knew about Christianity, and I did many negative things. I accepted Jesus Christ on October 1, 2004, and my life began to change. My negative behavior and hobbies were changing, but I still need to improve because I still saying bad words and play a lot of video games.'
]
