export const BenJianLi = [

  'Hello, my name is P.K. I am here to witness a true story about how GOD brought me to a new and abundant life! First of all, I would like to thank those people who bring me into God’s family. OK, let me start my story…',

  'Way way way back when I was five, I had already been going to a Christian school for a few years. As a little kid, I didn’t know God but to play around in school. I came to the United States of America when I was 8. I didn’t go to church for the next two years. Then, a friend of mine invited me to go a church in San Leandro. I went to that church, but after awhile, I quit because they didn’t have a program that I wanted, so I quit going to church for the next 5 years. After that I had vivid memories of going to a gospel center for summer tutoring, but I never went back after the summer program ended.',

  'Not paying attention to God, I lived my life the way I wanted without knowing the purpose of life. I was a person that slacked off in school and was very self-centered. I had been playing around in school. I wasted a lot of time on computer everyday. I even cut school a lot just to go home to play computer games. As the result, I got bad grades. And since I never cared about how others feel, I was cursing at others a lot too.',

  'Though I had forgotten all about God, God never forget me. This summer, God brought me to Him once again. He came a lot closer than before. He came to my life. He came to save me. One day I was so depressed, I asked myself a question: “Why do I even live in a world with pain?” I had no answer for that question and I had no purpose in living either. That night, I walked and walked and walked and walked till I passed by the community basketball court—a familiar place for me, a place where I always played basketball with my friends—however, tonight something was different, a group of Christians gathered there. At first I didn’t notice them. They were having a basketball night. I didn’t feel like being bothered, so I wanted to leave but everyone there were listening quietly and it didn’t look good to be the only one to get up. So I chose to stay for awhile and participated in their activities',

  "During the break time, God changed my life. I came to realize that I am a sinner in front of the righteous God. I needed God to wash away my sins. The Bible teaches us that all have missed the mark of God's perfection. This means that we are sinners and because God is morally perfect in every way, God alone is righteous. But God demonstrated His love to mankind by sending His only Son, Jesus Christ, to earth in order to die for the sinners of the world (for you and me) and thereby paying the penalty that each of us owed God, but could never pay!",

  'For those who personally place their trust in what Jesus did at the cross and receive Him into their lives as Lord and Savior, they become a child of God, a new creation! (John 1:12, II Cor. 5:17, Rev. 3:20). Becoming a Christian has nothing to do with things like attending church, being a morally upright person, or donating funds to religious groups. Rather, becoming a Christian begins with receiving the Lord Jesus Christ by faith as an act of the will. The basketball coach raised a question, “If you are willing to open your heart and let God in, please raise your hand”. At that time I raised my hand and accepted Jesus as my personal Savior. And it also answered my question that I had about the purpose of life. If you missed the question I asked myself earlier, let me repeat, I asked, “Why do I even live in a world with pain?’’ And the answer is God is here and He is willing to heal my pain and wash away my sins so I can have an abundant life, a life with purpose.',

  'From that day, I had already experienced God’s love me so I start going to church. I am allowing God to heal my pains. I find out that God’s words are really interesting and are leading me to an abundant life. I am happy to be in God’s family, learning to love and be loved.',

  'In church, through studying God’s Word and having fellowship with brothers and sisters, I came to realize that it is not good to cut school! Computer games can be addictive so I need to have self-control otherwise my brain will only think about games all day. I started to have a new life that I learn to care about others and not to slack off in school. Most importantly I learned to love and respect others even though they don’t respect me. I learned that with God, nothing is impossible.',

  'God is really willing to take all the pain that I had. He changes me in a way that I have never imagined. I got into the habit of reading His words. God has renewed me in many areas of my life. I found value in people and past experiences when I came to realize that God is there and has a plan and purpose for all. From now on, I will never ever forget GOD because GOD will never forget U!'
]
