export const BillyGuoSalvation = [

  "Hello everyone. My name is Billy Guo. Before accepting Jesus Christ, the relationshipbetween me and my mom was very complicated and difficult. I was brought to Oakland fromNew York and lived with my grandma when I was six-month-old. When I started living with mymom again in the year 2001, I was about five years old. It was very scary because I haven’t seenher for a long time. I couldn't address her as mom because it was really awkward to call her mom,and especially when she was very aggressive. It never got better because I couldn't defend myselfand I was always scared. It was never easy living with my mom because I often get yelled at foreating too slowly, or too neatly. It made me frustrated but I couldn't get mad in front of herbecause I would get in trouble. Since I was six months old, I had been living with my grandma,so I felt safe and knew that she would defend me from my mom.",

  "After my grandma passed away during 2011 when I was in 10th grade, I began to feelfrustrated at my mom. I blamed my mom for not seeing my grandma at the hospital, and notrespecting her when she was alive. But it changed this year, I transferred school and I wasinvited to Faith Jireh Christian Church. When we get together on fellowship, bible study andworship, the pastors invited me to accept Jesus Christ as my savior. Jesus is God. I accepted himbecause I believe that he died for me on the cross so my sins would be forgiven. I learned thateven though I didn't commit an actual crime like murder, but the inner anger that I had towardsmy mom is a sin. It doesn't sound serious to us but it's filthy in the eyes of the holy, righteousGod. It's sin that leads to death and separation from God. But in Christ, there is forgiveness ofsins, there is new life and everlasting life.",

  'When I accepted Jesus, I stopped blaming my mom even though my mom used to beabusive and make me do things by force. Now I forgive her because I know that we are allsinners. Jesus forgave my sins therefore I forgave my mom. Now, living with my mom becomesless complicated and difficult because I accepted Christ as my God and Savior. I feel easier totalk to her because there is no anger in my head, I am able to calm down and talk to her. She alsobecomes less aggressive and there are fewer arguments. Thank you, Jesus.',

  '“For if you forgive me when they sin against you, your heavenly Father will also forgive you. But if you do not forgive men their sins, your Father will not forgive your sins.” (Matthew 6:14-15)'
]
